apiVersion: v1
kind: Service
metadata:
  name: esphome
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 6052
      targetPort: 6052
      protocol: TCP
    - name: api
      port: 6053
      targetPort: 6053  # ESPHome API port
      protocol: TCP
  selector:
    app: esphome
